export const getBlogItems = () => [
  {
    date: "12-07-2021, 19:02",
    title: "Чудо-женщина на столе в Wonder Woman: Challenge of The Amazons",
    image: {
      src: "assets/img/articles.jpg",
      alt: "Настольная игра",
    },
    text: "Ravensburger уже 1-го марта выпустит в продажу игру коллективного дизайнера Prospero Hall (Horrified, Jaws, Villainous) кооператив на 2-5 человек – Чудо Женщина и её бравые амазонные солдаты.",
    link: "#",
    like: "1",
    id: "1",
  },
  {
    date: "12-07-2021, 17:15",
    title: "Чудо-женщина на столе в Wonder Woman: Challenge of The Amazons",
    image: {
      src: "assets/img/articles.jpg",
      alt: "Настольная игра",
    },
    text: "Ravensburger уже 1-го марта выпустит в продажу игру коллективного дизайнера Prospero Hall (Horrified, Jaws, Villainous) кооператив на 2-5 человек – Чудо Женщина и её бравые амазонные солдаты.",
    link: "#",
    like: "17",
    id: "2",
  },
  {
    date: "12-07-2021, 17:18",
    title: "Чудо-женщина на столе в Wonder Woman: Challenge of The Amazons",
    image: {
      src: "assets/img/articles.jpg",
      alt: "Настольная игра",
    },
    text: "Ravensburger уже 1-го марта выпустит в продажу игру коллективного дизайнера Prospero Hall (Horrified, Jaws, Villainous) кооператив на 2-5 человек – Чудо Женщина и её бравые амазонные солдаты.",
    link: "#",
    like: "83",
    id: "3",
  },
  {
    date: "12-07-2021, 17:01",
    title: "Чудо-женщина на столе в Wonder Woman: Challenge of The Amazons",
    image: {
      src: "assets/img/articles.jpg",
      alt: "Настольная игра",
    },
    text: "Ravensburger уже 1-го марта выпустит в продажу игру коллективного дизайнера Prospero Hall (Horrified, Jaws, Villainous) кооператив на 2-5 человек – Чудо Женщина и её бравые амазонные солдаты.",
    link: "#",
    like: "96",
    id: "4",
  },
  {
    date: "12-07-2021, 16:01",
    title: "Чудо-женщина на столе в Wonder Woman: Challenge of The Amazons",
    image: {
      src: "assets/img/articles.jpg",
      alt: "Настольная игра",
    },
    text: "Ravensburger уже 1-го марта выпустит в продажу игру коллективного дизайнера Prospero Hall (Horrified, Jaws, Villainous) кооператив на 2-5 человек – Чудо Женщина и её бравые амазонные солдаты.",
    link: "#",
    like: "41",
    id: "5",
  },
  {
    date: "12-07-2021, 11:01",
    title: "Чудо-женщина на столе в Wonder Woman: Challenge of The Amazons",
    image: {
      src: "assets/img/articles.jpg",
      alt: "Настольная игра",
    },
    text: "Ravensburger уже 1-го марта выпустит в продажу игру коллективного дизайнера Prospero Hall (Horrified, Jaws, Villainous) кооператив на 2-5 человек – Чудо Женщина и её бравые амазонные солдаты.",
    link: "#",
    like: "64",
    id: "6",
  },
  {
    date: "12-07-2021, 17:44",
    title: "Чудо-женщина на столе в Wonder Woman: Challenge of The Amazons",
    image: {
      src: "assets/img/articles.jpg",
      alt: "Настольная игра",
    },
    text: "Ravensburger уже 1-го марта выпустит в продажу игру коллективного дизайнера Prospero Hall (Horrified, Jaws, Villainous) кооператив на 2-5 человек – Чудо Женщина и её бравые амазонные солдаты.",
    link: "#",
    like: "173",
    id: "7",
  },
  {
    date: "12-07-2021, 17:08",
    title: "Чудо-женщина на столе в Wonder Woman: Challenge of The Amazons",
    image: {
      src: "assets/img/articles.jpg",
      alt: "Настольная игра",
    },
    text: "Ravensburger уже 1-го марта выпустит в продажу игру коллективного дизайнера Prospero Hall (Horrified, Jaws, Villainous) кооператив на 2-5 человек – Чудо Женщина и её бравые амазонные солдаты.",
    link: "#",
    like: "68",
    id: "8",
  },
  {
    date: "12-07-2021, 12:20",
    title: "Чудо-женщина на столе в Wonder Woman: Challenge of The Amazons",
    image: {
      src: "assets/img/articles.jpg",
      alt: "Настольная игра",
    },
    text: "Ravensburger уже 1-го марта выпустит в продажу игру коллективного дизайнера Prospero Hall (Horrified, Jaws, Villainous) кооператив на 2-5 человек – Чудо Женщина и её бравые амазонные солдаты.",
    link: "#",
    like: "97",
    id: "9",
  },
];
